ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Workspace" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."WorkspaceMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."OAuthState" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SocialAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."MediaAsset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Post" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PostVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PostTarget" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PostMedia" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PublishJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PublishAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."QueueSlot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."AnalyticsMetric" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PostTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."HashtagGroup" ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
  END IF;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated;
  END IF;
END $$;
